### ISSUE TITLE
[RO] [REVMAP] To-Do

### ISSUE THREAD

**Issue by BaxAndrei** [BaxAndreiRO/Dedications-Script#3]
## 🐞 Buguri
- NIMIC MOMENTAN

## :closed_book: Extrem de important
- [ ] aaduga tot ce e ramas din versiunea veche
- [ ] pagina parola pierduta de finalizat (+schimbare parola din link)

## :orange_book: Importanta majora
- [x] Rescrie programul sa folosească mysql
- [ ] sa se poata utiliza reset auto increment doar daca nu exista date pt elementul caruia doreste sa i-l reseteze
- [ ] Cand faci pagina de modificat conturi, previno modificare contului root.
- [ ] Inainte de release 1.0.0, adauga optiunea de demo_mode pentru a preveni anumite functii din a fi folosite (ex modificare parola, adaugare/stergere conturi, etc)
- [x] sa poata utiliza grecaptcha sau hrecaptcha

## :blue_book: Importanta minora
- [ ] Log pt erori
- [ ] Log pt avertismente
- [ ] Adauga la updater sa adauge/modifice/stearga/copiere(+la setări) pentru fiecare utilizator nou setari daca e cazul.
- [ ] posibilitate de a adauga numar pt whatsapp cand sunt dedicatiile pornite

**Comment by BaxAndrei** [comment]
Alte informatii posibil utile aici: https://github.com/BaxAndreiRO/Script-Dedicatii/issues/1

**Comment by BaxAndrei** [comment]
- [ ] posibilitate de a adauga numar pt whatsapp cand sunt dedicatiile pornite
